// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eazwcwxgapyjjjlehwrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhendjd3hnYXB5ampqbGVod3JkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NDg2ODUsImV4cCI6MjA2MTQyNDY4NX0.PkwMDMhwawMBQO8-gzRVGgOn0Fna3h-4UwqopM0_-PI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);